### ISSUE TITLE
PSO Iteration

### ISSUE THREAD

**Issue by mjmaher987** [AtheerAlgherairy/Cloudsim-FCFS-SJF-RR-PSO-#1]
Hello.

In the README file you mentioned that PSO iteration = 500.
Where did you set this attribute? I couldn't find the PSO iteration (for example in FCFS folder).

Best

**Comment by AtheerAlgherairy** [comment]
Check the run method in src/PSO/PSO.java
I set the for loop to 500 iterations

**Comment by mjmaher987** [comment]
I see, thanks.
